# Filling our Clubs database in one go
# make an epl dict
# loop through the dict
# commit club info to database
from models import connect_db, db, Clubs, Matches

# CREATE AND ADD CLUBS TO THE LEAGUE
clubs = [
    {
        "club_name_short": "MCY",
        "club_name_long": "Manchester City",
        "club_logo": "/static/img/ManchesterCity_wbg.png.cf.jpg",
        "wins": 7,
        "draws": 2,
        "losses": 2,
        "played": 11,
        "points": 23,
        "goals_for": 22,
        "goals_against": 6,
        "position": 2,
        "attack": 84,
        "midfield": 87,
        "defense": 85,
        "rating_ovr": 85,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "LIV",
        "club_name_long": "Liverpool",
        "club_logo": "/static/img/Liverpool_wbg.png.cf.jpg",
        "wins": 6,
        "draws": 4,
        "losses": 1,
        "played": 11,
        "points": 22,
        "goals_for": 31,
        "goals_against": 11,
        "position": 4,
        "attack": 86,
        "midfield": 83,
        "defense": 85,
        "rating_ovr": 84,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "MNU",
        "club_name_long": "Manchester United",
        "club_logo": "/static/img/ManchesterUnited_wbg.png.cf.jpg",
        "wins": 5,
        "draws": 2,
        "losses": 4,
        "played": 11,
        "points": 17,
        "goals_for": 19,
        "goals_against": 17,
        "position": 6,
        "attack": 85,
        "midfield": 83,
        "defense": 84,
        "rating_ovr": 84,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "CHE",
        "club_name_long": "Chelsea",
        "club_logo": "/static/img/Chelsea_wbg.png.cf.jpg",
        "wins": 8,
        "draws": 2,
        "losses": 1,
        "played": 11,
        "points": 26,
        "goals_for": 27,
        "goals_against": 4,
        "position": 1,
        "attack": 84,
        "midfield": 86,
        "defense": 82,
        "rating_ovr": 83,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "TOT",
        "club_name_long": "Tottenham",
        "club_logo": "/static/img/Tottenham_wbg.png.cf.jpg",
        "wins": 5,
        "draws": 1,
        "losses": 1,
        "played": 11,
        "points": 16,
        "goals_for": 9,
        "goals_against": 16,
        "position": 9,
        "attack": 90,
        "midfield": 81,
        "defense": 80,
        "rating_ovr": 81,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "LEI",
        "club_name_long": "Leicester City",
        "club_logo": "/static/img/LeicesterCity_wbg.png.cf.jpg",
        "wins": 4,
        "draws": 3,
        "losses": 4,
        "played": 11,
        "points": 15,
        "goals_for": 16,
        "goals_against": 18,
        "position": 12,
        "attack": 82,
        "midfield": 82,
        "defense": 78,
        "rating_ovr": 80,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "ARS",
        "club_name_long": "Arsenal",
        "club_logo": "/static/img/Arsenal_wbg.png.cf.jpg",
        "wins": 6,
        "draws": 2,
        "losses": 3,
        "played": 11,
        "points": 20,
        "goals_for": 13,
        "goals_against": 13,
        "position": 5,
        "attack": 83,
        "midfield": 79,
        "defense": 77,
        "rating_ovr": 79,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "WHU",
        "club_name_long": "West Ham United",
        "club_logo": "/static/img/WestHam_wbg.png.cf.jpg",
        "wins": 7,
        "draws": 2,
        "losses": 2,
        "played": 11,
        "points": 23,
        "goals_for": 23,
        "goals_against": 13,
        "position": 3,
        "attack": 79,
        "midfield": 79,
        "defense": 79,
        "rating_ovr": 79,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "EVE",
        "club_name_long": "Everton",
        "club_logo": "/static/img/Everton_wbg.png.cf.jpg",
        "wins": 4,
        "draws": 3,
        "losses": 4,
        "played": 11,
        "points": 15,
        "goals_for": 16,
        "goals_against": 16,
        "position": 11,
        "attack": 79,
        "midfield": 79,
        "defense": 79,
        "rating_ovr": 79,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "AVA",
        "club_name_long": "Aston Villa",
        "club_logo": "/static/img/AstonVilla2_wbg.png.cf.jpg",
        "wins": 3,
        "draws": 1,
        "losses": 7,
        "played": 11,
        "points": 10,
        "goals_for": 14,
        "goals_against": 20,
        "position": 16,
        "attack": 79,
        "midfield": 77,
        "defense": 77,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "WOL",
        "club_name_long": "Wolverhampton Wanderers",
        "club_logo": "/static/img/Wolverhampton2_wbg.png.cf.jpg",
        "wins": 5,
        "draws": 1,
        "losses": 5,
        "played": 11,
        "points": 216,
        "goals_for": 11,
        "goals_against": 12,
        "position": 8,
        "attack": 78,
        "midfield": 81,
        "defense": 77,
        "rating_ovr": 78,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "NEW",
        "club_name_long": "Newcastle United",
        "club_logo": "/static/img/Newcastle2_wbg.png.cf.jpg",
        "wins": 0,
        "draws": 5,
        "losses": 6,
        "played": 11,
        "points": 5,
        "goals_for": 12,
        "goals_against": 24,
        "position": 19,
        "attack": 79,
        "midfield": 74,
        "defense": 75,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "LEE",
        "club_name_long": "Leeds United",
        "club_logo": "/static/img/LeedsUnited_wbg.png.cf.jpg",
        "wins": 2,
        "draws": 5,
        "losses": 4,
        "played": 11,
        "points": 1,
        "goals_for": 11,
        "goals_against": 18,
        "position": 15,
        "attack": 77,
        "midfield": 77,
        "defense": 75,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "CRY",
        "club_name_long": "Crystal Palace",
        "club_logo": "/static/img/CrystalPalace_wbg.png.cf.jpg",
        "wins": 4,
        "draws": 6,
        "losses": 2,
        "played": 11,
        "points": 15,
        "goals_for": 15,
        "goals_against": 14,
        "position": 10,
        "attack": 77,
        "midfield": 76,
        "defense": 74,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "BRI",
        "club_name_long": "Brighton Hove Albion",
        "club_logo": "/static/img/BrightonHoveAlbion_wbg.png.cf.jpg",
        "wins": 4,
        "draws": 5,
        "losses": 2,
        "played": 11,
        "points": 17,
        "goals_for": 12,
        "goals_against": 12,
        "position": 11,
        "attack": 77,
        "midfield": 74,
        "defense": 76,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "SOU",
        "club_name_long": "Southampton",
        "club_logo": "/static/img/Southampton_wbg.png.cf.jpg",
        "wins": 3,
        "draws": 5,
        "losses": 3,
        "played": 11,
        "points": 14,
        "goals_for": 10,
        "goals_against": 12,
        "position": 13,
        "attack": 76,
        "midfield": 77,
        "defense": 74,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "BUR",
        "club_name_long": "Burnley",
        "club_logo": "/static/img/Burnley_wbg.png.cf.jpg",
        "wins": 1,
        "draws": 5,
        "losses": 5,
        "played": 11,
        "points": 8,
        "goals_for": 11,
        "goals_against": 17,
        "position": 18,
        "attack": 76,
        "midfield": 76,
        "defense": 76,
        "rating_ovr": 76,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "WAT",
        "club_name_long": "Watford",
        "club_logo": "/static/img/Watford_wbg.png.cf.jpg",
        "wins": 3,
        "draws": 1,
        "losses": 7,
        "played": 11,
        "points": 10,
        "goals_for": 12,
        "goals_against": 19,
        "position": 17,
        "attack": 75,
        "midfield": 76,
        "defense": 73,
        "rating_ovr": 75,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "NOR",
        "club_name_long": "Norwich City",
        "club_logo": "/static/img/NorwichCity_wbg.png.cf.jpg",
        "wins": 1,
        "draws": 2,
        "losses": 8,
        "played": 11,
        "points": 5,
        "goals_for": 5,
        "goals_against": 26,
        "position": 20,
        "attack": 74,
        "midfield": 74,
        "defense": 74,
        "rating_ovr": 74,
        "home_form": 5,
        "away_form": 5
    },
    {
        "club_name_short": "BRE",
        "club_name_long": "Brentford",
        "club_logo": "/static/img/Brentford_wbg.png.cf.jpg",
        "wins": 3,
        "draws": 3,
        "losses": 5,
        "played": 11,
        "points": 12,
        "goals_for": 13,
        "goals_against": 14,
        "position": 14,
        "attack": 72,
        "midfield": 74,
        "defense": 73,
        "rating_ovr": 73,
        "home_form": 5,
        "away_form": 5
    },
]
def add_clubs():
    for club in clubs:
        new_club = Clubs(
            club_name_short=club['club_name_short'],
            club_name_long=club['club_name_long'],
            club_logo=club['club_logo'],
            wins=club['wins'],
            losses=club['losses'],
            draws=club['draws'],
            played=club['played'],
            points=club['points'],
            position=club['position'],
            goals_for=club['goals_for'],
            goals_against=club['goals_against'],
            attack=club['attack'],
            midfield=club['midfield'],
            defense=club['defense'],
            rating_ovr=club['rating_ovr'],
            home_form=club['home_form'],
            away_form=club['away_form']
        )

        # add and commit the new club to our datbase
        db.session.add(new_club)
        db.session.commit()

epl_matches = [
    {
        'status': 'next',
        'gameweek': "Game Week 12",
        'matchlist': [
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '6:30 AM',
                "home_club": 'LEI',
                "away_club": 'CHE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'NEW',
                "away_club": 'BRE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'BUR',
                "away_club": 'CRY',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'AVA',
                "away_club": 'BRI',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'WAT',
                "away_club": 'MNU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'WOL',
                "away_club": 'WHU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'NOR',
                "away_club": 'SOU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '11:30 AM',
                "home_club": 'LIV',
                "away_club": 'ARS',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/21/2021',
                "time": '8:00 AM',
                "home_club": 'MCY',
                "away_club": 'EVE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/21/2021',
                "time": '10:30 AM',
                "home_club": 'TOT',
                "away_club": 'LEE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
        ]
    },
    {
        'status': 'upcoming',
        'gameweek': "Game Week 13",
        'matchlist': [
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '6:30 AM',
                "home_club": 'LEI',
                "away_club": 'CHE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'NEW',
                "away_club": 'BRE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'BUR',
                "away_club": 'CRY',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'AVA',
                "away_club": 'BRI',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'WAT',
                "away_club": 'MNU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'WOL',
                "away_club": 'WHU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '9:00 AM',
                "home_club": 'NOR',
                "away_club": 'SOU',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/20/2021',
                "time": '11:30 AM',
                "home_club": 'LIV',
                "away_club": 'ARS',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/21/2021',
                "time": '8:00 AM',
                "home_club": 'MCY',
                "away_club": 'EVE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
            {
                "status": "pending",
                "date": '11/21/2021',
                "time": '10:30 AM',
                "home_club": 'TOT',
                "away_club": 'LEE',
                "home_score": 0,
                "away_score": 0,
                "predicted_home_score": 0,
                "predicted_away_score": 0,
            },
        ]
    }
]
def add_matches():
    for week in epl_matches:
        for match in week['matchlist']:
            new_match = Matches(
                status=match['status'],
                date=match['date'],
                time=match['time'],
                home_club=match['home_club'],
                away_club=match['away_club'],
                home_score=match['home_score'],
                away_score=match['away_score'],
                predicted_home_score=match['predicted_home_score'],
                predicted_away_score=match['predicted_away_score'],
            )

            # add and commit the new club to our datbase
            db.session.add(new_match)
            db.session.commit()

def predict_matches():
    for week in epl_matches:
        if week['status'] == 'next':
            for match in week['matchlist']:
                for club in clubs:
                    home = 0
                    away = 0
                    if match['home_club'] == club['club_name_short']:
                        home = club['rating_ovr']
                    if match['away_club'] == club['club_name_short']:
                        away = club['rating_ovr']

                    if home > away:
                        match['predicted_home_score'] = 1
                        match['predicted_away_score'] = 0
                    elif home < away:
                        match['predicted_home_score'] = 0
                        match['predicted_away_score'] = 1
                    else:
                        match['predicted_home_score'] = 1
                        match['predicted_away_score'] = 1
